### ISSUE TITLE
Epic - Mejoras a la API

### ISSUE THREAD

**Issue by fdodino** [uqbar-project/wollok-ts#171]
## Migrar constantes de LSP IDE: 

- [x] `const LIST_MODULE = 'List'`  =>  ojo que tiene es 'wollok.lang.List'
- [x] `const STRING_MODULE = 'wollok.lang.String'`
- [x] `const WOLLOK_BASE_MODULES = 'wollok.'` =>  `WOLLOK_BASE_PACKAGE`
- [x] `const SELF = 'self'` =>  `KEYWORD.self`
- [x] extender Number, Boolean, Date, Pair, Range, Dictionary como constantes
- [x] extender el `toString` como constante de nombre de método
- [x] `isTestFile`, `isProgramFile`
- [x] extraer wtest, wpgm y wlk como constantes (extensiones de files)

revisar todas las que son de [diagram generator](https://github.com/uqbar-project/wollok-ts-cli/blob/master/src/services/diagram-generator.ts)

## Migrar esta función de LSP IDE:

```ts
function getImportedDefinitionsFromConsole(interpreter: Interpreter): string[] {
  const imports = interpreter.evaluation.environment.getNodeByFQN<Package>(REPL).imports
  return imports.flatMap(imp => imp.children.map(child => (child as unknown as Reference<Entity>).name))
}
```

pero extenderlo para cualquier nodo por fqn, porque la consola es un concepto propio de ts-cli.

## Mejorar de ts-cli

- [ ] uqbar-project/wollok-ts-cli#137
- [ ] De paso, castear children de un import para que sea de tipo Reference<Entity>
- [x] Hacer que el import devuelva las cosas que importa (dado que tiene el environment)
- [x] Hacer que el package tenga el mismo mensaje para devolver las cosas que importa, delegando en sus imports
- Hacer una revisión de wollok-ts-cli y de wollok-lsp-ide para ir agregando como task

**Comment by fdodino** [comment]
@nscarcella @PalumboN acá fui anotando las cosas que charlamos en Discord, siéntanse libres de agregar, acotar o modificar
