### ISSUE TITLE
[EPIC] Type System

### ISSUE THREAD

**Issue by PalumboN** [uqbar-project/wollok-ts#187]
Issue para usar de épica para tener un Sistema de Tipos _piola_

- [ ] Tirar una primera versión https://github.com/uqbar-project/wollok-ts/pull/152
- [ ] Tipar Lang!
- [ ] Mostrar info en el LSP
- [ ] Un montón de TODOs en este PR
- [ ] Migrar la página de la wiki a este repo o Lang https://github.com/uqbar-project/wollok/wiki/Constraints-based-Wollok-Type-System
